###
POST http://localhost:8080/post/create
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="example.png"
Content-Type: image/png

< .backend/src/main/kotlin/de/kaan/assets/post_images/
--WebAppBoundary
Content-Disposition: form-data; name="post_data"

{"text":"Das ist ein Beispieltext", "userId":566175986081599488}
--WebAppBoundary--
