###
POST http://localhost:8080/users/add
Content-Type: application/json

{
  "username": "Spanky Ham",
  "email": "ksentuerk@progeek.de"
}


###
POST http://localhost:8080/users/add
Content-Type: application/json

{
  "username": "TommusBlockus",
  "email": "tbecke@progeek.de",
  "password": "test"
}


###
DELETE http://localhost:8080/users/9


###
GET http://localhost:8080/users/allUsers