###
POST http://localhost:8080/users/add
Content-Type: application/json

{
  "username": "Spanky Ham",
  "email": "ksentuerk@progeek.de"
}


###
POST http://localhost:8080/users/add
Content-Type: application/json

{
  "username": "TommusBlockus",
  "email": "tbecke@progeek.de",
  "password": "test"
}


###
PUT /profile/update HTTP/1.1
Host: 192.168.1.125:8080
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="0d1cc102-c298-4647-a3bf-23601b3cc98b.jpg"
Content-Type: image/*

[Binary data of the image]

--boundary123
Content-Disposition: form-data;

{
  "userId": 1,
  "username": "Hallo",
  "email": "example@example.com"
}
--boundary123--
